// Generated by CoffeeScript 1.8.0
(function() {
  var del, gulp;

  gulp = require('gulp');

  del = require('del');

  gulp.task('test', function() {
    gulp.src("public");
    return console.log("mikakane hello");
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
