// Generated by CoffeeScript 1.8.0
(function() {
  var config, del, gulp;

  gulp = require('gulp');

  del = require('del');

  config = {
    bower: "bower_components/",
    libDir: "themes/casper/source/lib/"
  };

  gulp.task('clear', function(cb) {
    return del([config.libDir], cb);
  });

  gulp.task("lib/jquery", function() {
    return gulp.src("" + config.bower + "jquery/dist/*").pipe(gulp.dest("" + config.libDir + "jquery"));
  });

  gulp.task("lib/vue", function() {
    return gulp.src("" + config.bower + "vue/dist/*").pipe(gulp.dest("" + config.libDir + "vue"));
  });

  gulp.task("lib/bootstrap", function() {
    return gulp.src("" + config.bower + "bootstrap/dist/**/*").pipe(gulp.dest("" + config.libDir + "bootstrap"));
  });

  gulp.task('lib', ["lib/jquery", "lib/vue", "lib/bootstrap"]);

  gulp.task('test', function() {
    gulp.src("public");
    return console.log("mikakane hello");
  });

}).call(this);

//# sourceMappingURL=gulpfile.js.map
