# config
cover: //blog.ghost.org/content/images/2013/Nov/cover.png
logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
bio: 'Peridot craft, Make Future for physical computing. '

# top page

top: "peridot_release"

# Content
excerpt_link: Read More

# Miscellaneous
rss:
